// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/stock.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockAnalyser_GetStockDetail_FullMethodName = "/stockrpc.stockAnalyser/GetStockDetail"
)

// StockAnalyserClient is the client API for StockAnalyser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockAnalyserClient interface {
	GetStockDetail(ctx context.Context, in *Stockrequest, opts ...grpc.CallOption) (*StockResponse, error)
}

type stockAnalyserClient struct {
	cc grpc.ClientConnInterface
}

func NewStockAnalyserClient(cc grpc.ClientConnInterface) StockAnalyserClient {
	return &stockAnalyserClient{cc}
}

func (c *stockAnalyserClient) GetStockDetail(ctx context.Context, in *Stockrequest, opts ...grpc.CallOption) (*StockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockResponse)
	err := c.cc.Invoke(ctx, StockAnalyser_GetStockDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockAnalyserServer is the server API for StockAnalyser service.
// All implementations must embed UnimplementedStockAnalyserServer
// for forward compatibility.
type StockAnalyserServer interface {
	GetStockDetail(context.Context, *Stockrequest) (*StockResponse, error)
	mustEmbedUnimplementedStockAnalyserServer()
}

// UnimplementedStockAnalyserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockAnalyserServer struct{}

func (UnimplementedStockAnalyserServer) GetStockDetail(context.Context, *Stockrequest) (*StockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockDetail not implemented")
}
func (UnimplementedStockAnalyserServer) mustEmbedUnimplementedStockAnalyserServer() {}
func (UnimplementedStockAnalyserServer) testEmbeddedByValue()                       {}

// UnsafeStockAnalyserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockAnalyserServer will
// result in compilation errors.
type UnsafeStockAnalyserServer interface {
	mustEmbedUnimplementedStockAnalyserServer()
}

func RegisterStockAnalyserServer(s grpc.ServiceRegistrar, srv StockAnalyserServer) {
	// If the following call pancis, it indicates UnimplementedStockAnalyserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockAnalyser_ServiceDesc, srv)
}

func _StockAnalyser_GetStockDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stockrequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockAnalyserServer).GetStockDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockAnalyser_GetStockDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockAnalyserServer).GetStockDetail(ctx, req.(*Stockrequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockAnalyser_ServiceDesc is the grpc.ServiceDesc for StockAnalyser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockAnalyser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stockrpc.stockAnalyser",
	HandlerType: (*StockAnalyserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockDetail",
			Handler:    _StockAnalyser_GetStockDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stock.proto",
}
